# Generated by Django 4.0.2 on 2022-03-31 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newbooking',
            old_name='booking_id',
            new_name='bookid',
        ),
    ]
