# Generated by Django 4.0.2 on 2022-03-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_booking_id_newbooking_bookid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newbooking',
            old_name='bookid',
            new_name='booking_id',
        ),
    ]
