# Generated by Django 4.0.2 on 2022-04-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_bookid_newbooking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbooking',
            name='aadhar',
            field=models.FileField(upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='newbooking',
            name='form',
            field=models.FileField(upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='newbooking',
            name='pan',
            field=models.FileField(upload_to='files/%Y/%m/%d/'),
        ),
    ]
